"""Build a review-friendly CMeIE KG subset for Graph-RAG experiments."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.kg.cmeie_filter import CMeIEFilterConfig, build_review_kg


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Filter converted CMeIE KG triples into a smaller reviewed subgraph CSV."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=ROOT / "data" / "medical_kg" / "medical_kg_cmeie.csv",
        help="Input CMeIE KG CSV generated by prepare_cmeie_kg.py or download_cmeie_from_hf.py --convert.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "data" / "medical_kg" / "medical_kg_cmeie_reviewed.csv",
        help="Output reviewed CMeIE KG CSV. The main demo KG is not overwritten.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=ROOT / "outputs" / "logs" / "cmeie_review_kg_report.json",
        help="JSON report path for filter counters and relation distribution.",
    )
    parser.add_argument(
        "--max-triples",
        type=int,
        default=None,
        help="Optional maximum number of triples to keep.",
    )
    parser.add_argument(
        "--max-per-relation",
        type=int,
        default=2000,
        help="Maximum triples to keep for each mapped relation type.",
    )
    parser.add_argument(
        "--max-per-head",
        type=int,
        default=30,
        help="Maximum triples to keep for each head entity.",
    )
    parser.add_argument(
        "--max-entity-chars",
        type=int,
        default=40,
        help="Drop triples whose head or tail entity is longer than this value.",
    )
    args = parser.parse_args()

    config = CMeIEFilterConfig(
        max_entity_chars=args.max_entity_chars,
        max_triples=args.max_triples,
        max_per_relation=args.max_per_relation,
        max_per_head=args.max_per_head,
    )
    stats = build_review_kg(args.input, args.output, config=config, report_path=args.report)

    print(f"input_triples: {stats.input_triples}")
    print(f"kept_triples: {stats.kept_triples}")
    print(f"dropped_unmapped_relation: {stats.dropped_unmapped_relation}")
    print(f"dropped_invalid_text: {stats.dropped_invalid_text}")
    print(f"dropped_duplicates: {stats.dropped_duplicates}")
    print(f"dropped_by_limits: {stats.dropped_by_limits}")
    print(f"output: {stats.output_path}")
    print(f"report: {stats.report_path}")
    print("top_relations:")
    for relation, count in list(stats.relation_counts.items())[:10]:
        print(f"- {relation}: {count}")


if __name__ == "__main__":
    main()
